name: Daily update overlay feed

on:
  schedule:
    - cron: "0 */12 * * *"   # run every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure Swiss ephemeris files
      run: |
        mkdir -p $GITHUB_WORKSPACE/ephe
        cp *.se1 $GITHUB_WORKSPACE/ephe/

    - name: Run overlay builder
      run: |
        python scripts/build_overlays.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add docs/feed_overlay.json
        git commit -m "Daily update overlay feed" || echo "No changes"
        git push
