name: Build Live Transit Feed

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Optional note to append to commit message'
        required: false
        default: ''
      obs_lat:
        description: 'Observer latitude (deg) e.g., 39.653'
        required: false
        default: '39.653'
      obs_lon:
        description: 'Observer longitude (deg) e.g., -119.706'
        required: false
        default: '-119.706'
      obs_elev:
        description: 'Observer elevation (meters) e.g., 1340'
        required: false
        default: '1340'
  schedule:
    # 11:00 & 23:00 UTC = every 12h starting 04:00 Pacific
    - cron: '0 11,23 * * *'

permissions:
  contents: write

concurrency:
  group: live-feed-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Defaults; can be overridden via workflow_dispatch inputs
      OBS_LAT: ${{ github.event.inputs.obs_lat || '39.653' }}
      OBS_LON: ${{ github.event.inputs.obs_lon || '-119.706' }}
      OBS_ELEV: ${{ github.event.inputs.obs_elev || '1340' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install numpy>=1.26,<2.0 astropy>=5.3,<7.0 astroquery>=0.4.7,<0.5
          fi

      - name: Generate JPL feed
        run: |
          python scripts/generate_feed.py

      - name: Add Swiss angles + Arabic Parts
        run: |
          python scripts/augment_feed.py

      - name: Show first lines of feed_now.json (debug)
        run: |
          test -f docs/feed_now.json && head -n 120 docs/feed_now.json || (echo "docs/feed_now.json missing" && exit 1)

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feed_now.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            msg="chore(feed): update feed_now.json [skip ci]"
            if [ -n "${{ github.event.inputs.note }}" ]; then
              msg="$msg - ${{ github.event.inputs.note }}"
            fi
            git commit -m "$msg"
            git push
          fi

      - name: Upload feed artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: feed_now.json
          path: docs/feed_now.json
