name: Build

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Optional note to append to commit message'
        required: false
        default: ''
  schedule:
    # 11:00 & 23:00 UTC = 04:00 & 16:00 Pacific
    - cron: '0 11,23 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate raw feed (JPL w/ Swiss fallback)
        run: |
          python scripts/fetch_transits.py \
            --config config/live_config.json \
            --out docs/feed_now.json

      - name: Add Swiss Angles + Arabic Parts
        run: |
          python scripts/compute_angles_and_parts.py \
            --feed docs/feed_now.json \
            --targets config/live_config.json \
            --out docs/feed_now.json

      - name: Merge overlay with natal charts
        run: |
          python scripts/build_overlays.py \
            --feed docs/feed_now.json \
            --config config/live_config.json \
            --out docs/feed_overlay.json

      - name: Show first lines of feed (debug)
        run: |
          head -n 80 docs/feed_now.json || true
          head -n 40 docs/feed_overlay.json || true

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feed_now.json docs/feed_overlay.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            msg="chore(feed): update feeds [skip ci]"
            if [ -n "${{ github.event.inputs.note }}" ]; then
              msg="$msg - ${{ github.event.inputs.note }}"
            fi
            git commit -m "$msg"
            git push
          fi
