name: Generate 60-Day Transit Feed

on:
  schedule:
    - cron: "0 11 1 */2 *"   # run every 2 months at 11:00 UTC on day 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install pyswisseph astroquery pytz

      - name: Verify committed ephemeris files
        run: |
          echo "Checking for all required Swiss Ephemeris files..."
          ls -lh .
          # Core planetary & asteroid files
          test -f sepl_18.se1   && echo "✅ sepl_18.se1   (planets Sun–Pluto)"       || (echo "❌ Missing sepl_18.se1" && exit 1)
          test -f seas_18.se1   && echo "✅ seas_18.se1   (asteroids core, Chiron)" || (echo "❌ Missing seas_18.se1" && exit 1)
          test -f seasm18.se1   && echo "✅ seasm18.se1   (asteroids supplementary)"|| (echo "❌ Missing seasm18.se1" && exit 1)
          # Moon precision files
          test -f semo_18.se1   && echo "✅ semo_18.se1   (Moon high precision)"    || (echo "❌ Missing semo_18.se1" && exit 1)
          test -f semom18.se1   && echo "✅ semom18.se1   (Moon motion corrections)"|| (echo "❌ Missing semom18.se1" && exit 1)
          # Combined planetary/lunar file
          test -f seplm18.se1   && echo "✅ seplm18.se1   (Planets + Moon motions)" || (echo "❌ Missing seplm18.se1" && exit 1)

      - name: Generate 60-day feed
        run: python scripts/generate_feed_60day.py

      - name: Commit & push updated feed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/feed_60day.json
          git commit -m "Update 60-day transit feed" || echo "No changes"
          git push
