name: Update live transit feed

on:
  schedule:
    # Every 12 hours starting at 04:00 Pacific (04:00 and 16:00 PT)
    # PDT (UTC-7) -> 11:00 and 23:00 UTC
    - cron: '0 11,23 * * *'
  workflow_dispatch:
    inputs:
      overlay_charts:
        description: 'Comma-separated natal names to overlay (optional). Example: Tommy,Milena'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run transits fetch script
        env:
          OVERLAY_CHARTS: ${{ github.event.inputs.overlay_charts }}
        run: |
          python scripts/fetch_transits.py

      - name: Commit generated docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs || true
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: update transit feeds (auto)" || true
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
