name: Update transit feeds

on:
  schedule:
    - cron: "0 11 * * *"   # 04:00 PT
    - cron: "0 23 * * *"   # 16:00 PT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure Swiss path
        run: |
          mkdir -p .eph
          echo "SE_EPHE_PATH=$GITHUB_WORKSPACE/.eph" >> $GITHUB_ENV

      - name: Generate JPL feed
        run: |
          python scripts/fetch_transits.py --config config/live_config.json --out docs/feed_now.json

      - name: Show first lines of feed_now.json (debug)
        run: |
          python - << 'PY'
          import json, itertools
          p='docs/feed_now.json'
          d=json.load(open(p,'r',encoding='utf-8'))
          print('generated_at_utc:', d.get('generated_at_utc'))
          for o in itertools.islice(d.get('objects',[]), 0, 10):
              print(o.get('id'), o.get('targetname'), 'ecl_lon_deg=', o.get('ecl_lon_deg'),
                    'RA=', o.get('ra_deg'), 'DEC=', o.get('dec_deg'))
          PY

      - name: Add Swiss angles + Arabic Parts
        run: |
          python scripts/compute_angles_and_parts.py --feed docs/feed_now.json --targets config/targets.json --out docs/feed_now.json

      - name: Commit if changed
        run: |
          git diff --quiet || (
            git config user.name "github-actions[bot]" &&
            git config user.email "github-actions[bot]@users.noreply.github.com" &&
            git add docs &&
            git commit -m "chore: update transit feeds (auto)" &&
            git push
          )
